# Generated by Django 2.2 on 2020-07-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='finished',
            new_name='finish_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done')], default='new', max_length=15, verbose_name='Status'),
        ),
    ]
