# Generated by Django 2.2 on 2020-07-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200721_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detailed_desc',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Detailed description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done')], default='new', max_length=15, verbose_name='Status'),
        ),
    ]
